version: '2'
services:
  mysql_kafka:
    image: debezium/example-mysql:0.10
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - kafka-network
  connect:
    image: debezium/connect:0.10
    ports:
      - "8083:8083"
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - BOOTSTRAP_SERVERS=[kafka_public_IP]:9092
    networks:
      - kafka-network

volumes:
  mysql-volume:
networks:
  kafka-network:
